config/routes.rb
Ndc::Application.routes.draw do

  scope "/ec" do

    get "tempmedias/remove/:grid_id" => "tempmedias#remove" , :as=>:remove_tempmedia
    get "tempmedias/show" => "tempmedias#show" , :as=>:show_tempmedias
    get "tempmedias" => "tempmedias#index" , :as=>:tempmedias
    post "tempmedias/upload" => "tempmedias#upload" , :as=>:upload_tempmedias

    get "oauth/authorize"=>"auth#authorize"       ,as: :authorize
    post "oauth/authorizeit"=>"auth#authorizeit"  ,as: :authorizeit
    post "oauth/access_token"=>"auth#access_token" ,as: :access_token
    get "welcome/index"
    get "home"=>"welcome#home",as: :home
    get "login"=>"auth#login"   ,as: :login
    get "login/lwqzx"=>"auth#lwqzx"
    get "auth_lwqzx"=>"auth#auth_lwqzx"
    post "auth"=>"auth#auth"    ,as: :auth
    get "logout"=>"auth#logout" ,as: :logout
    get "download/:id" => "grid#download" , :as=>:download
    get "see/:id" => "grid#see" , :as=>:see

    get 'api/user' => "api/user#index" 

    get 'jiaoan/remove_attach'=> "jiaoans#remove_attach" ,as: :remove_jiaoan_attach
    get 'hub/remove_attach'=> "hubs#remove_attach" ,as: :remove_hub_attach
    get 'jiaoan_album/:id/print' => "jiaoan_albums#print", as: :print_jiaoan_album
    match 'user/settings' => "users#settings", :as => :user_settings, :via=>[:get,:post]

    get 'groups/type/:type'=>'groups#type'
    match "users/search"   => "users#search"  , :as => :search_users, :via=>[:get,:post]
    match "groups/search"  => "groups#search",  :as => :search_groups, :via=>[:get,:post]
    match "pages/search"   => "pages#search"  , :as => :search_pages, :via=>[:get,:post]
    get "pages/name/:name"   => "pages#name"  , :as => :page_name
    match "courses/search" => "courses#search", :as => :search_courses, :via=>[:get,:post]
    match "apps/search" => "apps#search", :as => :search_apps, :via=>[:get,:post]
    match "semesters/search" => "semesters#search", :as => :search_semesters, :via=>[:get,:post]
    match "crlogs/search" => "crlogs#search", :as => :search_crlogs, :via=>[:get,:post]
    post "crlog/reply" => "crlogs#reply", :as => :crlog_reply
    get "crlog/remove_reply/:id/:reply_id" =>"crlogs#remove_reply", :as=>:remove_reply
    match "teachers/search" => "teachers#search", :as => :search_teachers, :via=>[:get,:post]
    match "students/search" => "students#search", :as => :search_students, :via=>[:get,:post]
    match "students/upload" => "students#upload", :as => :upload_students, :via=>[:get,:post]
    match "courses/upload" => "courses#upload", :as => :upload_courses, :via=>[:get,:post]

    match "seats/search" => "seats#search", :as => :search_seats, :via=>[:get,:post]

    resources :cr_applies do
      member do
        get :change_status
      end
      collection do 
        get :export
      end
    end
    resources :jiaoan_albums do
      resources :jiaoans
    end

    resources :hubs do
      resources :submissions
      member do 
        get :package
      end
    end
    resources :roles
    resources :students
    resources :submissions
    resources :teachers
    resources :tokens
    resources :apps
    resources :pages
    resources :sites
    resources :users do
      collection do 
        get :upload
        post :upload
      end
    end
    resources :courses
    resources :semesters
    resources :groups
    resources :cr_schedules do
      collection do 
        get :get_latest
      end
    end
    resources :crlogs
    resources :seats

    root 'welcome#index'

  end
end

app/models/crlog.rb
# -*- encoding : utf-8 -*-
class Crlog
  include Mongoid::Document
  include Mongoid::Timestamps
  field :semester, type: String
  field :croom, type: String
  field :banji, type: String
  field :use_date, type: Date
  field :course_name, type: String
  field :jiece, type: String
  field :computer_status, type: String
  field :garbage_status, type: String
  field :place_status, type: String
  field :status, type: String
  field :loger, type: String
  field :closed_by, type: String
  field :desc, type: String
  embeds_many :crlog_replys
  index({semester: 1})
  index({croom: 1})
  index({banji: 1})
  index({use_date: 1})
  index({course_name: 1})
  index({loger: 1})
  index({created_at: 1})
end

app/controllers/crlogs_controller.rb
# -*- encoding : utf-8 -*-
class CrlogsController < ApplicationController
  before_action :basic_infos_required
  before_action :teacher_required
  before_action :root_required, only: [:edit,:update,:destroy]
  before_action :set_crlog, only: [:show, :edit, :update, :destroy]
  before_action :check_loger, only: [:edit,:update,:destroy]

  def check_loger
    if @crlog.loger!=realname
      redirect_to :back, flash: {error: "你不能操作别人的东西"}
    end
  end

  def remove_reply
    @crlog = Crlog.find(params[:id])
    reply=@crlog.crlog_replys.find(params[:reply_id])
    if @crlog.crlog_replys.delete(reply)
      redirect_to :back, flash: {notice: "回复删除成功"}
    else
      redirect_to :back, flash: {error: "回复删除失败"}
    end
  end

  def reply
    @crlog = Crlog.find(params[:crlog_id])
    @crlog_reply=@crlog.crlog_replys.create(reply: params[:reply],replyer: realname)
    if @crlog.save
      redirect_to :back , notice: "回复成功"
    else
      redirect_to :back , flash: {error: "回复成功"}
    end
  end

  def search
    hsh={}
    hsh[:croom] = params[:croom] unless params[:croom].blank?
    hsh[:banji] = params[:banji] unless params[:banji].blank?
    hsh[:course_name] = params[:course_name] unless params[:course_name].blank?
    hsh[:jiece] = params[:jiece] unless params[:jiece].blank?
    hsh[:use_date] = params[:use_date] unless params[:use_date].blank?
    hsh[:loger] = /#{params[:loger]}/ unless params[:loger].blank?
    @crlogs=Crlog.where(hsh).desc("created_at").page  params[:page]
    render :index
  end

  # GET /crlogs
  # GET /crlogs.json
  def index
    hsh={}
    hsh[:loger]=realname unless params[:loger].blank?
    params[:week] ||=current_week
    params[:week]=1 if params[:week].to_i<=0
    if current_semester
      sm_name=current_semester.full_name
    else
      sm_name=params[:semester] 
    end
    @semester=Semester.where(full_name: sm_name).first
    @begin_on,@end_on = week_range(@semester,params[:week])
    @crlogs = Crlog.where(hsh).gte(use_date: @begin_on).lte(use_date: @end_on)
  end

  # GET /crlogs/1
  # GET /crlogs/1.json
  def show
  end

  # GET /crlogs/new
  def new
    @crlog = Crlog.new
    @crlog.use_date ||= Time.now.strftime("%Y-%m-%d")
  end

  # GET /crlogs/1/edit
  def edit
  end

  # POST /crlogs
  # POST /crlogs.json
  def create
    @crlog = Crlog.new(crlog_params)

    respond_to do |format|
      if @crlog.save
        format.html { redirect_to crlogs_path(anchor: "/#{@crlog.croom}"), notice: '日志已经成功创建' }
        format.json { render action: 'show', status: :created, location: @crlog }
      else
        format.html { render action: 'new' }
        format.json { render json: @crlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crlogs/1
  # PATCH/PUT /crlogs/1.json
  def update
    respond_to do |format|
      if @crlog.update(crlog_params)
        format.html { redirect_to crlogs_path(anchor: "/#{@crlog.croom}"), notice: '日志已经成功更新' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @crlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crlogs/1
  # DELETE /crlogs/1.json
  def destroy
    @crlog.destroy
    respond_to do |format|
      format.html { redirect_to crlogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crlog
      @crlog = Crlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crlog_params
      params[:crlog][:loger]=realname
      params[:crlog][:semester]=current_semester.full_name
      params.require(:crlog).permit(:croom, :semester, :banji, :use_date, :course_name, :jiece, :computer_status, :garbage_status, :place_status, :status, :loger,  :desc)
    end
end

app/helpers/crlogs_helper.rb
# -*- encoding : utf-8 -*-
module CrlogsHelper
end

app/views/crlogs/_form.html.slim
= form_for @crlog , html: {class: 'ui form segment'} do |f|
  - if @crlog.errors.any?
    #error_explanation
      h2 = "#{pluralize(@crlog.errors.count, "error")} prohibited this crlog from being saved:"
      ul
        - @crlog.errors.full_messages.each do |message|
          li = message

  .three.fields
    .field
      label 电脑室:
      .ui.fluid.selection.dropdown
        input type='hidden' name='crlog[croom]' value=@crlog.croom 
          .default.text = @crlog.croom 
          i.dropdown.icon
          .menu
            - @crooms.each do |cm|
              .item data-value="#{cm}" #{cm}
    .field
      label 班级:
      .ui.fluid.selection.dropdown
        input type='hidden' name='crlog[banji]' value=@crlog.banji
          .default.text = @crlog.banji
          i.dropdown.icon
          .menu
            - @banjis.each do |banji|
              .item data-value="#{banji}" #{banji}
    .field
      = f.label '使用日期'
      = f.text_field :use_date, type: "date"
  .three.fields
    .field
      label 课程名称:
      .ui.fluid.selection.dropdown
        input type='hidden' name='crlog[course_name]' value=@crlog.course_name
          .default.text = @crlog.course_name
          i.dropdown.icon
          .menu
            - @courses.each do |course|
              .item data-value="#{course}" #{course}
    .field
      label 节次:
      .ui.fluid.selection.dropdown
        input type='hidden' name='crlog[jiece]' value=@crlog.jiece
          .default.text = @crlog.jiece
          i.dropdown.icon
          .menu
            - @jieces.each do |jc|
              .item data-value="#{jc}" #{jc}
  .ui.tabular.filter.menu
    a.active.item data-tab="hardware" 电脑硬件
    a.item data-tab="environment" 卫生情况
    a.item data-tab="arrangement" 设施摆放
    a.item data-tab="others" 本次课软件硬件情况
  .ui.tab.active.top.attached data-tab="hardware"
    = f.text_area :computer_status 
  .ui.tab data-tab="environment"
    = f.text_area :garbage_status
  .ui.tab data-tab="arrangement"
    = f.text_area :place_status
  .ui.tab data-tab="others"
    = f.text_area :desc
  p
    .actions = f.submit '保存', class: 'ui green  button'

app/views/crlogs/edit.html.slim
h2 日志编辑

== render 'form'

=' link_to '查看', @crlog  , class: 'ui button'
=' link_to '返回', crlogs_path, class: 'ui button'

app/views/crlogs/index.html.slim
.ui.header #{@semester ? @semester.full_name : ""}第(#{params[:week]})周电脑室使用日志

= form_tag crlogs_path ,method: "get", class: 'ui form' do
  .inline.field
    .ui.selection.dropdown
      - if current_semester
        - sm = current_semester.full_name
      - else
        - sm = ""
      input type='hidden' name='semester' value=sm
        .default.text 学期 
        i.dropdown.icon
        .menu
          - @semesters.each do |sm|
            .item data-value="#{sm}" #{sm}
    .ui.selection.dropdown
      input type='hidden' name='week' value=current_week 
        .default.text 教学周 
        i.dropdown.icon
        .menu
          - 1.upto(23) do |i|
            .item data-value="#{i}" #{i}
    =<> text_field_tag :loger ,realname
    =<> submit_tag '搜索', class: 'ui green button'


- if false
  = form_tag search_crlogs_path , class: 'ui form' do
    .inline.field
      .ui.selection.dropdown
        input type='hidden' name='croom'  
          .default.text 电脑室 
          i.dropdown.icon
          .menu
            - @crooms.each do |cm|
              .item data-value="#{cm}" #{cm}
      .ui.selection.dropdown
        input type='hidden' name='banji' 
          .default.text 班级
          i.dropdown.icon
          .menu
            - @banjis.each do |banji|
              .item data-value="#{banji}" #{banji}
      = text_field_tag :use_date ,nil, placeholder: Time.now.strftime("%Y-%m-%d")
      .ui.selection.dropdown
        input type='hidden' name='course_name' 
          .default.text 课程名称
          i.dropdown.icon
          .menu
            - @courses.each do |course|
              .item data-value="#{course}" #{course}
      .ui.selection.dropdown
        input type='hidden' name='jiece' 
          .default.text 节次
          i.dropdown.icon
          .menu
            - @jieces.each do |jc|
              .item data-value="#{jc}" #{jc}
      =<> text_field_tag :loger ,realname

      =<> submit_tag '搜索', class: 'ui green button'

.ui.tabular.filter.menu
  - @crooms.each do |croom|
    - if croom=="C303" 
      a.active.item data-tab=croom = croom
    - else
      a.item data-tab=croom = croom
- @crooms.each do |croom|
  - act = croom=="C303" ? "ui active tab" : "ui tab"
  div class=act  data-tab=croom
    = cache("#{croom}_#{params[:week]}_crlog",expires_in: 1.minutes) do
      table.ui.table.celled.segment
        thead
          th 节次
          th 星期一
          th 星期二
          th 星期三
          th 星期四
          th 星期五
          th 星期六
        tbody
          - @jieces.each do |jiece|
            tr
              td 第#{jiece}节
              - 1.upto(6) do |dd|
                - theday = @begin_on+(dd-1).days
                - log = @crlogs.where(croom: croom,jiece: jiece, use_date: theday).first
                td 
                  - if log
                    p
                      - unless log.computer_status.blank?
                        .ui.red.label data-html=log.computer_status data-position="top center" 硬件
                      - unless log.garbage_status.blank?
                        .ui.red.label data-html=log.garbage_status 卫生
                      - unless log.place_status.blank?
                        .ui.red.label data-html=log.place_status 摆放
                      - unless log.desc.blank?
                        .ui.red.label data-html=log.desc 其它
                      - unless log.crlog_replys.blank?
                        .ui.green.circular.label = log.crlog_replys.count
                    p 
                      = link_to log.banji.to_s+"("+log.loger.to_s+")",log


p 
  =<> link_to '新日志', new_crlog_path , class: 'ui green button'
  =<> link_to '上一周', crlogs_path(week: params[:week].to_i-1) , class: 'ui green button'

app/views/crlogs/index_new.html.slim
.ui.header 电脑室使用日志

= form_tag search_crlogs_path , class: 'ui form' do
  .inline.field
    .ui.selection.dropdown
      input type='hidden' name='croom'  
        .default.text 电脑室 
        i.dropdown.icon
        .menu
          - @crooms.each do |cm|
            .item data-value="#{cm}" #{cm}
    .ui.selection.dropdown
      input type='hidden' name='banji' 
        .default.text 班级
        i.dropdown.icon
        .menu
          - @banjis.each do |banji|
            .item data-value="#{banji}" #{banji}
    = text_field_tag :use_date ,nil, placeholder: Time.now.strftime("%Y-%m-%d")
    .ui.selection.dropdown
      input type='hidden' name='course_name' 
        .default.text 课程名称
        i.dropdown.icon
        .menu
          - @courses.each do |course|
            .item data-value="#{course}" #{course}
    .ui.selection.dropdown
      input type='hidden' name='jiece' 
        .default.text 节次
        i.dropdown.icon
        .menu
          - @jieces.each do |jc|
            .item data-value="#{jc}" #{jc}
    =<> text_field_tag :loger ,realname

    =<> submit_tag '搜索', class: 'ui green button'

table.ui.table.segment
  thead
    th 
    th 回复
    th 使用日期
    th 电脑室
    th 节次
    th 硬件
    th 卫生
    th 摆放
    th 本次 
    th 状态
    th 登记人
    th
    th
    th

  - @crlogs.each do |crlog|
    tr
      td = @num+=1
      td 
        - if crlog.crlog_replys
          .ui.green.circular.label 
            = link_to crlog.crlog_replys.count , crlog , class: 'noline'
        - else
          .ui.red.circular.label 0
      td = crlog.use_date
      td = crlog.croom
      td = crlog.jiece
      td 
        - unless crlog.computer_status.blank?
          .ui.red.circular.label
        - else
          .ui.green.circular.label
      td 
        - unless crlog.garbage_status.blank?
          .ui.red.circular.label
        - else
          .ui.green.circular.label
      td 
        - unless crlog.place_status.blank?
          .ui.red.circular.label
        - else
          .ui.green.circular.label
      td 
        - unless crlog.desc.blank?
          .ui.red.circular.label
        - else
          .ui.green.circular.label
      td = crlog.status
      td = crlog.loger
      td = link_to '详细', crlog, class: 'ui mini button'
      - if is_root?
        td = link_to '编辑', edit_crlog_path(crlog),class: "ui mini button" if crlog.loger==realname
        td = link_to '删除', crlog, class: "ui mini button", data: {:confirm => 'Are you sure?'}, :method => :delete if crlog.loger==realname

p
  = link_to '新日志', new_crlog_path , class: 'ui green button'

app/views/crlogs/new.html.slim
.ui.header 电脑室使用情况登记

== render 'form'

= link_to '返回', crlogs_path(anchor: "/C301"), class: "ui button"

app/views/crlogs/show.html.slim
.ui.header
  = link_to raw("<i class='ui left arrow icon'></i>"), crlogs_path,class: "noline"
  = @crlog.use_date.strftime("%Y-%m-%d")+ " "
  = @crlog.jiece+"节"
  = @crlog.croom+"室"
  = @crlog.banji+"班"
  = @crlog.course_name
  |使用情况登记
.ui.divider
.ui.grid
  .two.wide.column
    = @crlog.loger
  .fourteen.wide.column
    .ui.top.attached.message
      = @crlog.loger + " "+@crlog.created_at.to_fmt1+" 记录"
    .ui.attached.segment
      - unless @crlog.computer_status.blank?
        p: strong 电脑硬件状况:
        div  = @crlog.computer_status
      - unless @crlog.garbage_status.blank?
        p: strong 电脑室卫生状况:
        div  = @crlog.garbage_status
      - unless @crlog.place_status.blank?
        p: strong 电脑设施是否摆放整齐:
        div  = @crlog.place_status
      - unless @crlog.desc.blank?
        p: strong 其它情况:
        div = @crlog.desc
- unless @crlog.crlog_replys.blank?
  - @crlog.crlog_replys.each do |reply|
    .ui.grid
      .two.wide.column
        = reply.replyer
      .fourteen.wide.column
        .ui.top.attached.message
          = reply.replyer + " "+  reply.created_at.to_fmt1+" 回复"
          - if reply.replyer==realname
            =<> link_to "删除",remove_reply_path(@crlog,reply), class: "ui red mini button"
        .ui.attached.segment
          = reply.reply
.ui.divider
.ui.grid
  .two.wide.column
    p = image_tag "default_avatar.png", size: '48x48'
    p = realname
  .ui.fourteen.wide.column
    .ui.top.attached.message 回复:
    .ui.attached.segment
      = form_tag crlog_reply_path,class: 'ui form' do
        = hidden_field_tag "crlog_id",@crlog.id
        = text_area_tag "reply",nil,placeholder: "在此回复"
        p = submit_tag "回复", class: 'ui button'