config/routes.rb
Ndc::Application.routes.draw do

  scope "/ec" do

    get "tempmedias/remove/:grid_id" => "tempmedias#remove" , :as=>:remove_tempmedia
    get "tempmedias/show" => "tempmedias#show" , :as=>:show_tempmedias
    get "tempmedias" => "tempmedias#index" , :as=>:tempmedias
    post "tempmedias/upload" => "tempmedias#upload" , :as=>:upload_tempmedias

    get "oauth/authorize"=>"auth#authorize"       ,as: :authorize
    post "oauth/authorizeit"=>"auth#authorizeit"  ,as: :authorizeit
    post "oauth/access_token"=>"auth#access_token" ,as: :access_token
    get "welcome/index"
    get "home"=>"welcome#home",as: :home
    get "login"=>"auth#login"   ,as: :login
    get "login/lwqzx"=>"auth#lwqzx"
    get "auth_lwqzx"=>"auth#auth_lwqzx"
    post "auth"=>"auth#auth"    ,as: :auth
    get "logout"=>"auth#logout" ,as: :logout
    get "download/:id" => "grid#download" , :as=>:download
    get "see/:id" => "grid#see" , :as=>:see

    get 'api/user' => "api/user#index" 

    get 'jiaoan/remove_attach'=> "jiaoans#remove_attach" ,as: :remove_jiaoan_attach
    get 'hub/remove_attach'=> "hubs#remove_attach" ,as: :remove_hub_attach
    get 'jiaoan_album/:id/print' => "jiaoan_albums#print", as: :print_jiaoan_album
    match 'user/settings' => "users#settings", :as => :user_settings, :via=>[:get,:post]

    get 'groups/type/:type'=>'groups#type'
    match "users/search"   => "users#search"  , :as => :search_users, :via=>[:get,:post]
    match "groups/search"  => "groups#search",  :as => :search_groups, :via=>[:get,:post]
    match "pages/search"   => "pages#search"  , :as => :search_pages, :via=>[:get,:post]
    get "pages/name/:name"   => "pages#name"  , :as => :page_name
    match "courses/search" => "courses#search", :as => :search_courses, :via=>[:get,:post]
    match "apps/search" => "apps#search", :as => :search_apps, :via=>[:get,:post]
    match "semesters/search" => "semesters#search", :as => :search_semesters, :via=>[:get,:post]
    match "crlogs/search" => "crlogs#search", :as => :search_crlogs, :via=>[:get,:post]
    post "crlog/reply" => "crlogs#reply", :as => :crlog_reply
    get "crlog/remove_reply/:id/:reply_id" =>"crlogs#remove_reply", :as=>:remove_reply
    match "teachers/search" => "teachers#search", :as => :search_teachers, :via=>[:get,:post]
    match "students/search" => "students#search", :as => :search_students, :via=>[:get,:post]
    match "students/upload" => "students#upload", :as => :upload_students, :via=>[:get,:post]
    match "courses/upload" => "courses#upload", :as => :upload_courses, :via=>[:get,:post]

    match "seats/search" => "seats#search", :as => :search_seats, :via=>[:get,:post]

    resources :cr_applies do
      member do
        get :change_status
      end
      collection do 
        get :export
      end
    end
    resources :jiaoan_albums do
      resources :jiaoans
    end

    resources :hubs do
      resources :submissions
      member do 
        get :package
      end
    end
    resources :roles
    resources :students
    resources :submissions
    resources :teachers
    resources :tokens
    resources :apps
    resources :pages
    resources :sites
    resources :users do
      collection do 
        get :upload
        post :upload
      end
    end
    resources :courses
    resources :semesters
    resources :groups
    resources :cr_schedules do
      collection do 
        get :get_latest
      end
    end
    resources :crlogs
    resources :seats

    root 'welcome#index'

  end
end

app/models/jiaoan_album.rb
# -*- encoding : utf-8 -*-
class JiaoanAlbum
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :creator, type: String
  field :cooperators, type: String
  field :logo, type: Hash
  has_many :jiaoans, dependent: :restrict, autosave: true

  index({name: 1})
  index({creator: 1})
  index({created_at: 1})
end

app/controllers/jiaoan_albums_controller.rb
# -*- encoding : utf-8 -*-
class JiaoanAlbumsController < ApplicationController
  before_action :teacher_required
  before_action :set_jiaoan_album, only: [:show, :edit, :update, :print, :destroy]
  before_action :check_creator, only: [:edit, :update, :destroy]
  before_action :check_cooperators, only: [:print]
  before_action :only=>["create","update"] do
    logo_check("jiaoan_album") 
  end


  def check_cooperators
    unless @jiaoan_album.cooperators.include?(realname) or @jiaoan_album.creator==realname
      redirect_to :back, flash: {error: "你不能进行操作"}
    end
  end

  def check_creator
    unless is_root? or @jiaoan_album.creator==realname
      redirect_to :back, flash: {error: "你不能进行操作"}
    end
  end

  # GET /jiaoan_albums
  # GET /jiaoan_albums.json
  def index
    @jiaoan_albums = JiaoanAlbum.all.page params[:page]
  end

  # GET /jiaoan_albums/1
  # GET /jiaoan_albums/1.json
  def show
  end

  # GET /jiaoan_albums/new
  def new
    @jiaoan_album = JiaoanAlbum.new
  end

  def print
    @jiaoans = @jiaoan_album.jiaoans
    render layout: 'print'
  end

  # GET /jiaoan_albums/1/edit
  def edit
  end

  # POST /jiaoan_albums
  # POST /jiaoan_albums.json
  def create
    @jiaoan_album = JiaoanAlbum.new(jiaoan_album_params)

    respond_to do |format|
      if @jiaoan_album.save
        format.html { redirect_to jiaoan_albums_path, notice: '教案集创建成功' }
        format.json { render action: 'show', status: :created, location: @jiaoan_album }
      else
        format.html { render action: 'new' }
        format.json { render json: @jiaoan_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jiaoan_albums/1
  # PATCH/PUT /jiaoan_albums/1.json
  def update
    respond_to do |format|
      if @jiaoan_album.update(jiaoan_album_params)
        format.html { redirect_to jiaoan_albums_path, notice: '教案集更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @jiaoan_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jiaoan_albums/1
  # DELETE /jiaoan_albums/1.json
  def destroy
    @jiaoan_album.destroy
    grid.delete(@jiaoan_album.logo["grid_id"])
    respond_to do |format|
      format.html { redirect_to jiaoan_albums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jiaoan_album
      @jiaoan_album = JiaoanAlbum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jiaoan_album_params
      params.require(:jiaoan_album).permit(:name, :creator, :cooperators, :logo => [:grid_id,:filename,:content_type,:file_size])
    end
end

app/helpers/jiaoan_albums_helper.rb
# -*- encoding : utf-8 -*-
module JiaoanAlbumsHelper
end

app/views/jiaoan_albums/_form.html.slim
= form_for @jiaoan_album ,html: {multipart: true,class: "ui form segment"} do |f|
  - if @jiaoan_album.errors.any?
    #error_explanation
      h2 = "#{pluralize(@jiaoan_album.errors.count, "error")} prohibited this jiaoan_album from being saved:"
      ul
        - @jiaoan_album.errors.full_messages.each do |message|
          li = message

  .field
    = f.label "教案集名称"
    = f.text_field :name
  .two.fields
    .field
      = f.label "创建者"
      = f.text_field :creator, value: realname
    .field
      = f.label "合作者"
      = f.text_field :cooperators
  .field
    = f.label "标志"
    = file_field_tag :logo ,class: 'ui input'
  .actions = f.submit '保存', class: "ui small green button"

app/views/jiaoan_albums/edit.html.slim
.ui.header 编辑教案集

== render 'form'

app/views/jiaoan_albums/index.html.slim
h2 教案集

table.ui.table.segment
  thead
    th
    th 名称
    th 创建者
    th 合作者 
    th 标志
    th

  - @jiaoan_albums.each do |jiaoan_album|
    tr
      td = @num+=1
      td = link_to jiaoan_album.name, jiaoan_album
      td = jiaoan_album.creator
      td = jiaoan_album.cooperators
      td = image_tag(see_path(jiaoan_album.logo['grid_id'])) if jiaoan_album.logo
      td 
        =<> link_to "写教案",new_jiaoan_album_jiaoan_path(jiaoan_album.id), class: "ui mini green button"
        =<> link_to "查看教案",jiaoan_album_jiaoans_path(jiaoan_album.id), class: "ui mini teal button"
        =<> link_to "打印教案",print_jiaoan_album_path(jiaoan_album.id), class: "ui mini teal button"
        =<> link_to '编辑', edit_jiaoan_album_path(jiaoan_album), class: "ui mini button"
        =<> link_to '删除', jiaoan_album, data: {:confirm => 'Are you sure?'}, :method => :delete, class: "ui mini red button" if jiaoan_album.creator==realname


p = link_to '新教案集', new_jiaoan_album_path, class: "ui small green button"

app/views/jiaoan_albums/new.html.slim
.ui.header 新教案集

== render 'form'

app/views/jiaoan_albums/print.html.slim
- @jiaoans.each do |jiaoan|
  h3 = jiaoan.name
  div = raw jiaoan.content
  div.page_break

app/views/jiaoan_albums/show.html.slim
p
  strong 教案集名称 
  = @jiaoan_album.name
p
  strong 创建者
  = @jiaoan_album.creator
p
  strong 合作者
  = @jiaoan_album.cooperators
p
  = image_tag(see_path(@jiaoan_album.logo['grid_id'])) if @jiaoan_album.logo