config/routes.rb
Ndc::Application.routes.draw do

  scope "/ec" do

    get "tempmedias/remove/:grid_id" => "tempmedias#remove" , :as=>:remove_tempmedia
    get "tempmedias/show" => "tempmedias#show" , :as=>:show_tempmedias
    get "tempmedias" => "tempmedias#index" , :as=>:tempmedias
    post "tempmedias/upload" => "tempmedias#upload" , :as=>:upload_tempmedias

    get "oauth/authorize"=>"auth#authorize"       ,as: :authorize
    post "oauth/authorizeit"=>"auth#authorizeit"  ,as: :authorizeit
    post "oauth/access_token"=>"auth#access_token" ,as: :access_token
    get "welcome/index"
    get "home"=>"welcome#home",as: :home
    get "login"=>"auth#login"   ,as: :login
    get "login/lwqzx"=>"auth#lwqzx"
    get "auth_lwqzx"=>"auth#auth_lwqzx"
    post "auth"=>"auth#auth"    ,as: :auth
    get "logout"=>"auth#logout" ,as: :logout
    get "download/:id" => "grid#download" , :as=>:download
    get "see/:id" => "grid#see" , :as=>:see

    get 'api/user' => "api/user#index" 

    get 'jiaoan/remove_attach'=> "jiaoans#remove_attach" ,as: :remove_jiaoan_attach
    get 'hub/remove_attach'=> "hubs#remove_attach" ,as: :remove_hub_attach
    get 'jiaoan_album/:id/print' => "jiaoan_albums#print", as: :print_jiaoan_album
    match 'user/settings' => "users#settings", :as => :user_settings, :via=>[:get,:post]

    get 'groups/type/:type'=>'groups#type'
    match "users/search"   => "users#search"  , :as => :search_users, :via=>[:get,:post]
    match "groups/search"  => "groups#search",  :as => :search_groups, :via=>[:get,:post]
    match "pages/search"   => "pages#search"  , :as => :search_pages, :via=>[:get,:post]
    get "pages/name/:name"   => "pages#name"  , :as => :page_name
    match "courses/search" => "courses#search", :as => :search_courses, :via=>[:get,:post]
    match "apps/search" => "apps#search", :as => :search_apps, :via=>[:get,:post]
    match "semesters/search" => "semesters#search", :as => :search_semesters, :via=>[:get,:post]
    match "crlogs/search" => "crlogs#search", :as => :search_crlogs, :via=>[:get,:post]
    post "crlog/reply" => "crlogs#reply", :as => :crlog_reply
    get "crlog/remove_reply/:id/:reply_id" =>"crlogs#remove_reply", :as=>:remove_reply
    match "teachers/search" => "teachers#search", :as => :search_teachers, :via=>[:get,:post]
    match "students/search" => "students#search", :as => :search_students, :via=>[:get,:post]
    match "students/upload" => "students#upload", :as => :upload_students, :via=>[:get,:post]
    match "courses/upload" => "courses#upload", :as => :upload_courses, :via=>[:get,:post]

    match "seats/search" => "seats#search", :as => :search_seats, :via=>[:get,:post]

    resources :cr_applies do
      member do
        get :change_status
      end
      collection do 
        get :export
      end
    end
    resources :jiaoan_albums do
      resources :jiaoans
    end

    resources :hubs do
      resources :submissions
      member do 
        get :package
      end
    end
    resources :roles
    resources :students
    resources :submissions
    resources :teachers
    resources :tokens
    resources :apps
    resources :pages
    resources :sites
    resources :users do
      collection do 
        get :upload
        post :upload
      end
    end
    resources :courses
    resources :semesters
    resources :groups
    resources :cr_schedules do
      collection do 
        get :get_latest
      end
    end
    resources :crlogs
    resources :seats

    root 'welcome#index'

  end
end

app/views/shared/_flash_box.slim
.row
  .three.wide.column
  .ten.center.aligned.wide.column
    - if flash[:error]
      .ui.error.message = flash[:error] 
    - if flash[:notice]
      .ui.success.message = flash[:notice] 
  .three.wide.column

app/views/shared/_footer.slim
.ui.page.grid
  .ui.horizontal.icon.divider
    i.circular.heart.icon
  .footer
    .ui.three.column.grid
      .column
        .ui.bulleted.list
          .item = link_to "老师守则",page_name_path("老师守则")
          .item = link_to "学生守则",page_name_path("学生守则")
          .item = link_to "管理员守则",page_name_path("管理员守则")
      .column
        .ui.bulleted.list
          .item = link_to "机房介绍",page_name_path("机房介绍")
          .item = link_to "机房清洁安排表",page_name_path("清洁安排")

app/views/shared/_js.slim
javascript:
  $('.ui.dropdown').dropdown();
  $('.ui.checkbox').checkbox();
  $('.filter.menu .item').tab();
  $('.ui.popup').popup();
  $('.ui.modal').modal();

app/views/shared/_top_menu.slim
.ui.fixed.transparent.inverted.main.menu
  .ui.page.grid
    .item 
      i.home.icon
      =' link_to '电脑室管理',root_path(trailing_slash: true)
    - if is_teacher?
      .item
        =' link_to "上机申请",cr_applies_path
      .item
        =' link_to "机房日志",crlogs_path
      .item
        =' link_to "学生座位",seats_path
      .item 
        = link_to '文件上交',hubs_path
    
    - if is_root?
      .ui.dropdown.item
        |管理面板
        i.dropdown.icon
        .menu
          .item 
            i.doc.basic.icon
            = link_to '文章管理',pages_path
          .item 
            i.doc.basic.icon
            = link_to '教案管理',jiaoan_albums_path
          .item 
            i.id.basic.icon
            = link_to "帐号管理",users_path
          .item 
            i.user.basic.icon
            = link_to '老师管理',teachers_path
          .item 
            i.user.basic.icon
            = link_to '学生管理',students_path
          .item 
            i.community.basic.icon
            = link_to '群组管理',groups_path
          .item 
            i.community.basic.icon
            = link_to '角色管理',roles_path
          .item 
            i.basic.book.icon
            = link_to '课程管理',courses_path
          .item 
            i.date.basic.icon
            = link_to '学期管理',semesters_path
          .item 
            i.calendar.icon
            = link_to '上机安排',cr_schedules_path
          .item 
            i.globe.basic.icon
            = link_to '站点管理',sites_path
          .item 
            i.key.icon
            = link_to '应用管理',apps_path
          .item
            i.legal.icon
            = link_to '授权管理',tokens_path
    .right.menu
      - if login?
        .ui.dropdown.item
          = cu+"_"+realname+"("+default_group.to_s+")" 
          i.dropdown.icon
          .menu
            .item  
              = link_to "密码修改",edit_user_path(user_id) 
            .item
              = link_to "教学设置",user_settings_path

        i.sign.out.icon 
        =' link_to '登出', logout_path, class: 'item'
      - else
        i.sign.in.icon 
        /=' link_to '登录', login_path ,class: 'item'
        =' link_to '登录', auth_lwqzx_path ,class: 'item'