config/routes.rb
Ndc::Application.routes.draw do

  scope "/ec" do

    get "tempmedias/remove/:grid_id" => "tempmedias#remove" , :as=>:remove_tempmedia
    get "tempmedias/show" => "tempmedias#show" , :as=>:show_tempmedias
    get "tempmedias" => "tempmedias#index" , :as=>:tempmedias
    post "tempmedias/upload" => "tempmedias#upload" , :as=>:upload_tempmedias

    get "oauth/authorize"=>"auth#authorize"       ,as: :authorize
    post "oauth/authorizeit"=>"auth#authorizeit"  ,as: :authorizeit
    post "oauth/access_token"=>"auth#access_token" ,as: :access_token
    get "welcome/index"
    get "home"=>"welcome#home",as: :home
    get "login"=>"auth#login"   ,as: :login
    get "login/lwqzx"=>"auth#lwqzx"
    get "auth_lwqzx"=>"auth#auth_lwqzx"
    post "auth"=>"auth#auth"    ,as: :auth
    get "logout"=>"auth#logout" ,as: :logout
    get "download/:id" => "grid#download" , :as=>:download
    get "see/:id" => "grid#see" , :as=>:see

    get 'api/user' => "api/user#index" 

    get 'jiaoan/remove_attach'=> "jiaoans#remove_attach" ,as: :remove_jiaoan_attach
    get 'hub/remove_attach'=> "hubs#remove_attach" ,as: :remove_hub_attach
    get 'jiaoan_album/:id/print' => "jiaoan_albums#print", as: :print_jiaoan_album
    match 'user/settings' => "users#settings", :as => :user_settings, :via=>[:get,:post]

    get 'groups/type/:type'=>'groups#type'
    match "users/search"   => "users#search"  , :as => :search_users, :via=>[:get,:post]
    match "groups/search"  => "groups#search",  :as => :search_groups, :via=>[:get,:post]
    match "pages/search"   => "pages#search"  , :as => :search_pages, :via=>[:get,:post]
    get "pages/name/:name"   => "pages#name"  , :as => :page_name
    match "courses/search" => "courses#search", :as => :search_courses, :via=>[:get,:post]
    match "apps/search" => "apps#search", :as => :search_apps, :via=>[:get,:post]
    match "semesters/search" => "semesters#search", :as => :search_semesters, :via=>[:get,:post]
    match "crlogs/search" => "crlogs#search", :as => :search_crlogs, :via=>[:get,:post]
    post "crlog/reply" => "crlogs#reply", :as => :crlog_reply
    get "crlog/remove_reply/:id/:reply_id" =>"crlogs#remove_reply", :as=>:remove_reply
    match "teachers/search" => "teachers#search", :as => :search_teachers, :via=>[:get,:post]
    match "students/search" => "students#search", :as => :search_students, :via=>[:get,:post]
    match "students/upload" => "students#upload", :as => :upload_students, :via=>[:get,:post]
    match "courses/upload" => "courses#upload", :as => :upload_courses, :via=>[:get,:post]

    match "seats/search" => "seats#search", :as => :search_seats, :via=>[:get,:post]

    resources :cr_applies do
      member do
        get :change_status
      end
      collection do 
        get :export
      end
    end
    resources :jiaoan_albums do
      resources :jiaoans
    end

    resources :hubs do
      resources :submissions
      member do 
        get :package
      end
    end
    resources :roles
    resources :students
    resources :submissions
    resources :teachers
    resources :tokens
    resources :apps
    resources :pages
    resources :sites
    resources :users do
      collection do 
        get :upload
        post :upload
      end
    end
    resources :courses
    resources :semesters
    resources :groups
    resources :cr_schedules do
      collection do 
        get :get_latest
      end
    end
    resources :crlogs
    resources :seats

    root 'welcome#index'

  end
end

app/models/cr_apply.rb
class CrApply
  include Mongoid::Document
  include Mongoid::Timestamps
  field :applyer, type: String
  field :semester, type: String
  field :croom, type: String
  field :banji, type: String
  field :course, type: String
  field :wday, type: String
  field :jiece, type: String
  field :status,type: Boolean
  index({applyer: 1})
  index({semester: 1})
  index({croom: 1})
  index({banji: 1})
  index({course: 1})
  index({wday: 1})
  index({jiece: 1})
  index({status: 1})
end

app/controllers/cr_applies_controller.rb
class CrAppliesController < ApplicationController
  before_action :teacher_required, except: [:export]
  before_action :set_cr_apply, only: [:change_status,:show, :edit, :update, :destroy]
  before_action :check_applyer, only: [:edit,:update,:destroy]

  def check_applyer
    unless @cr_apply.applyer==realname or is_root?
      redirect_to :back, flash: {error: "你不能进行这个操作"}
    end
  end

  def export
    unless params[:status].blank?
      if params[:status]=="up"
        status=true
      elsif params[:status]=="down"
        status=false
      end
      @cr_applies = CrApply.where(status: status,semester: current_semester.full_name).all
    else
      @cr_applies = CrApply.where(semester: current_semester.full_name).all
    end
  end


  def change_status
    if request.xhr?
      if params[:status]=="up"
        status=true
      else
        status=false
      end
      @cr_apply.update_attribute(:status,status)
      respond_to do |form|
        form.js { render :layout=>false}
      end
    end
  end

  # GET /cr_applies
  # GET /cr_applies.json
  def index
    @tnames=CrApply.distinct("applyer")
    if params[:tname]
      @cr_applies = CrApply.where(applyer: params[:tname],semester: current_semester.full_name).all
    else
      @cr_applies = CrApply.where(semester: current_semester.full_name).all
    end
  end

  # GET /cr_applies/1
  # GET /cr_applies/1.json
  def show
  end

  # GET /cr_applies/new
  def new
    @cr_apply = CrApply.new
    @user=User.find(user_id)
    if @user.config
    unless @user.config.blank?
      unless @user.config[:fav_courses].blank?
        @courses=@user.config[:fav_courses]
      end
    end
    end
    @cr_apply.applyer ||= realname
  end

  def edit
  end

  # POST /cr_applies
  # POST /cr_applies.json
  # params.require(:cr_apply).permit(:applyer, :semester, :croom, :course, :wday, :jiece)
  def create
    applys=params[:applys].compact.reject(&:empty?)
    unless applys.blank?
      applys.each do |apply|
        infos=apply.split("_")
        hsh={}
        hsh[:applyer]=params[:applyer]
        hsh[:banji]=params[:banji]
        hsh[:semester]=current_semester.full_name
        hsh[:croom]=infos[1]
        hsh[:course]=infos[0]
        hsh[:wday]=infos[2]
        hsh[:jiece]=infos[3]
        hsh[:status]=false
        cr_apply=CrApply.new(hsh)
        cr_apply.save
      end
      redirect_to cr_applies_path ,notice: "申请已经提交"
    else
      redirect_to :back ,flash: {error: "你没有任何选择"}
    end
  end

  # PATCH/PUT /cr_applies/1
  # PATCH/PUT /cr_applies/1.json
  def update
    respond_to do |format|
      if @cr_apply.update(cr_apply_params)
        format.html { redirect_to @cr_apply, notice: 'Cr apply was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cr_apply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cr_applies/1
  # DELETE /cr_applies/1.json
  def destroy
    @cr_apply.destroy
    respond_to do |format|
      format.html { redirect_to cr_applies_url }
      format.json { head :no_content }
      format.js { render :layout=>false}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cr_apply
    @cr_apply = CrApply.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cr_apply_params
    params.require(:cr_apply).permit(:applyer,:banji, :semester, :croom, :course, :wday, :jiece)
  end
end

app/helpers/cr_applies_helper.rb
module CrAppliesHelper
end

app/views/cr_applies/_form.html.slim
= form_for @cr_apply, html: {class: "ui form segment"} do |f|
  - if @cr_apply.errors.any?
    #error_explanation
      h2 = "#{pluralize(@cr_apply.errors.count, "error")} prohibited this cr_apply from being saved:"
      ul
        - @cr_apply.errors.full_messages.each do |message|
          li = message

  .inline.field
    label 申请人：
    = text_field_tag :applyer, @cr_apply.applyer
    .ui.selection.dropdown
      input type='hidden' name="banji" value=@cr_apply.banji
        .default.text 班级 
        i.dropdown.icon
        .menu
          - @banjis.each do |banji|
            .item data-value=banji =banji
  .ui.tabular.filter.menu
    - @crooms.each do |croom|
      - if croom=="C303" 
        a.active.item data-tab=croom = croom
      - else
        a.item data-tab=croom = croom
  - @crooms.each do |croom|
    - act = croom=="C303" ? "ui active tab" : "ui tab"
    div class=act  data-tab=croom
      table.ui.table.celled.segment
        thead
          th 节次
          th 星期一
          th 星期二
          th 星期三
          th 星期四
          th 星期五
        tbody
          - @jieces.each do |jiece|
            tr
              td 第#{jiece}节
              - 1.upto(5) do |wday|
                td  
                  .ui.fluid.selection.dropdown
                    input type='hidden' name="applys[]"
                      .default.text  
                      i.dropdown.icon
                      .menu
                        - @courses.each do |course|
                          .item data-value="#{course}_#{croom}_#{wday}_#{jiece}" #{course}

  p.actions = f.submit '申请', class: "ui green button"

app/views/cr_applies/change_status.js.slim
- if @cr_apply.status
  == "$('span.#{@cr_apply.id}').css('font-weight','bold');"
- else
  == "$('span.#{@cr_apply.id}').css('font-weight','normal');"

app/views/cr_applies/destroy.js.slim
== "$('span.#{@cr_apply.id}').fadeOut(1000);"

app/views/cr_applies/edit.html.slim
.ui.header 编辑上机申请

= form_for @cr_apply ,html: {class: "ui form"} do |f|
  .inline.field
    = f.label '申请者'
    = f.text_field :applyer
    .ui.selection.dropdown
      input type='hidden' name='cr_apply[croom]' value=@cr_apply.croom
        .default.text = @cr_apply.croom
        i.dropdown.icon
        .menu
          - @crooms.each do |t|
            .item data-value="#{t}" #{t}

    .ui.selection.dropdown
      input type='hidden' name='cr_apply[banji]' value=@cr_apply.banji
        .default.text = @cr_apply.banji
        i.dropdown.icon
        .menu
          - @banjis.each do |t|
            .item data-value="#{t}" #{t}
    .ui.selection.dropdown
      input type='hidden' name='cr_apply[course]' value=@cr_apply.course
        .default.text = @cr_apply.course
        i.dropdown.icon
        .menu
          - @courses.each do |t|
            .item data-value="#{t}" #{t}
    .ui.selection.dropdown
      input type='hidden' name='cr_apply[wday]' value=@cr_apply.wday
        .default.text = @cr_apply.wday
        i.dropdown.icon
        .menu
          - (1..5).each do |t|
            .item data-value="#{t}" #{t}
    .ui.selection.dropdown
      input type='hidden' name='cr_apply[jiece]' value=@cr_apply.jiece
        .default.text = @cr_apply.jiece
        i.dropdown.icon
        .menu
          - (1..7).each do |t|
            .item data-value="#{t}" #{t}
  .actions
    = submit_tag "保存", class: "ui green button"

= link_to '查看', @cr_apply
= link_to '返回', cr_applies_path

app/views/cr_applies/export.html.slim
table.ui.table.celled.segment
  thead
    th 节次
    th 星期一
    th 星期二
    th 星期三
    th 星期四
    th 星期五
  tbody
    - @jieces.each do |jiece|
      tr
        td 第#{jiece}节
        - 1.upto(5) do |wday|
          td  
            - @crooms.each do |croom|
              - @applys = @cr_applies.where(wday: wday,jiece: jiece,croom: croom)
              - if params[:status]=="up"
                - @applys = @cr_applies.where(status: true,wday: wday,jiece: jiece,croom: croom)
              - if params[:status]=="down"
                - @applys = @cr_applies.where(status: false,wday: wday,jiece: jiece,croom: croom)
              - unless @applys.blank?
                - @applys.each do |apply|
                  - if apply.status
                    strong = croom+ " "+ apply.applyer+" "+apply.banji.to_s
                  - else
                    = croom + " " +apply.applyer + " "+apply.banji
                  br

app/views/cr_applies/index.html.slim
= cache(user_id+"_"+"cr_apply"+params[:status].to_s,expires_in: 1.minutes) do
  .ui.header 上机申请列表

  .ui.tabular.filter.menu
    a.active.item data-tab="all" 全部
    - @crooms.each do |croom|
      a.item data-tab=croom = croom
  .ui.active.tab data-tab="all"
    p
      =<> link_to "全部",cr_applies_path,class: "ui mini button"
      =<> link_to "通过的",cr_applies_path(status: "up"),class: "ui mini button"
      =<> link_to "未通过的",cr_applies_path(status: "down"),class: "ui mini button"
    - if is_root?
      = form_tag cr_applies_path ,class: "ui form",method: "get" do 
        .inline.field
          .ui.selection.dropdown
            input type='hidden' name='tname'  
              .default.text 
              i.dropdown.icon
              .menu
                - @tnames.each do |nm|
                  .item data-value="#{nm}" #{nm}
          =submit_tag "查询", class: "ui mini button"
        
    table.ui.table.celled.segment
      thead
        th 节次
        th 星期一
        th 星期二
        th 星期三
        th 星期四
        th 星期五
      tbody
        - @jieces.each do |jiece|
          tr
            td 第#{jiece}节
            - 1.upto(5) do |wday|
              td  
                - @crooms.each do |croom|
                  - @applys = @cr_applies.where(wday: wday,jiece: jiece,croom: croom)
                  - if params[:status]=="up"
                    - @applys = @cr_applies.where(status: true,wday: wday,jiece: jiece,croom: croom)
                  - if params[:status]=="down"
                    - @applys = @cr_applies.where(status: false,wday: wday,jiece: jiece,croom: croom)
                  - unless @applys.blank?
                    - @applys.each do |apply|
                      span class=apply.id
                        - if apply.status
                          strong 
                            = link_to croom+" "+ apply.applyer,apply, title: apply.banji.to_s+apply.course.to_s
                        - else
                          = link_to croom+" "+apply.applyer,apply,title: apply.banji.to_s+apply.course.to_s
                        - if is_root?
                          = link_to raw("<i class='ui green thumbs up icon '></i>"),change_status_cr_apply_path(apply.id,status: "up"),remote: true
                          = link_to raw("<i class='ui red thumbs down icon '></i>"),change_status_cr_apply_path(apply.id,status: "down"),remote: true
                        - if apply.applyer==realname or is_root?
                          = link_to raw("<i class='ui red remove circle icon '></i>"),cr_apply_path(apply.id),remote: true, method: "delete",confirm: "真的要删除这个上机申请吗?"
                          = link_to raw("<i class='ui edit icon '></i>"),edit_cr_apply_path(apply)
                        br
                        
  - @crooms.each do |croom|
    .ui.tab  data-tab=croom
      table.ui.table.celled.segment
        thead
          th 节次
          th 星期一
          th 星期二
          th 星期三
          th 星期四
          th 星期五
        tbody
          /= cache("#{params[:week]}_crlog",expires_in: 1.minute) do
          - @jieces.each do |jiece|
            tr
              td 第#{jiece}节
              - 1.upto(5) do |wday|
                td  
                  - @applys = @cr_applies.where(wday: wday,jiece: jiece,croom: croom)
                  - unless @applys.blank?
                    - @applys.each do |apply|
                      span class=apply.id
                        - if apply.status
                          =<> croom+" "+ apply.applyer
                          =<> apply.banji.to_s

                        - else
                          =<> croom+" "+ apply.applyer
                          =<> apply.banji.to_s
                        - if is_root?
                          = link_to raw("<i class='ui green thumbs up icon '></i>"),change_status_cr_apply_path(apply.id,status: "up"),remote: true
                          = link_to raw("<i class='ui red thumbs down icon '></i>"),change_status_cr_apply_path(apply.id,status: "down"),remote: true
                        - if apply.applyer==realname or is_root?
                          = link_to raw("<i class='ui red remove circle icon '></i>"),cr_apply_path(apply.id),remote: true, method: "delete",confirm: "真的要删除这个上机申请吗?"
                          = link_to raw("<i class='ui edit icon '></i>"),edit_cr_apply_path(apply)
                      br

  p 
    =<> link_to '申请上机', new_cr_apply_path ,class: "ui green button"
    - if is_root?
      =<> link_to '设置为上机安排表', get_latest_cr_schedules_path ,class: "ui green button"

app/views/cr_applies/new.html.slim
.ui.header 上机申请

== render 'form'

p = link_to '返回', cr_applies_path, class: "ui button"

app/views/cr_applies/show.html.slim
p
  strong 申请人:
  = @cr_apply.applyer
p
  strong 学期:
  = @cr_apply.semester
p
  strong 电脑室:
  = @cr_apply.croom
p
  strong 课程:
  = @cr_apply.course
p
  strong 班级:
  = @cr_apply.banji
p
  strong 星期几:
  = @cr_apply.wday
p
  strong 节次:
  = @cr_apply.jiece

=<> link_to '编辑', edit_cr_apply_path(@cr_apply) ,class: "ui button"
=<> link_to '返回', cr_applies_path, class: "ui button"